<?php
try{
    if(!array_key_exists('ppid', $_POST)) throw new Exception('Не задана тех.карта');
    $ppid = $_POST['ppid'];
    $pp = engine::DB()->getRow('SELECT * FROM @[prefix]pp WHERE id = ?s AND archived = 0 AND deleted = 0', $ppid);
    if(!$pp) throw new Exception('Техкарта не найдена');

    $pp['data'] = json_decode($pp['data'], true);

    $countBMod = engine::DB()->getOne('SELECT COUNT(id) FROM @[prefix]modifications WHERE `name` LIKE \''.engine::CONFIG()['moysklad']['basicModification'].'%\' AND productId = ?s', $pp['productId']);

    $modName = engine::CONFIG()['moysklad']['basicModification'] . (($countBMod) ? ($countBMod + 1) : '1');

    $modId = engine::FACTORY()->createModification($pp['productId'], $modName, engine::USERS()->getCurrentUser()['id'], $pp['id']);
    if($modId['status'] == false) throw new Exception($modId['reason']);
    else $modId = $modId['id'];


    $revision = 0;

    engine::DB()->query('INSERT INTO @[prefix]specification (modificationId, revision, productId, fileId, canBeProduced, comment, created, createdBy, ppid) VALUES (?i, ?s, ?s, ?i, ?i, ?s, NOW(), ?i, ?s)', $modId, $revision, $pp['productId'], -1, 1, 'autogenerated', engine::USERS()->getCurrentUser()['id'], $pp['id']);
    $specificationId = engine::DB()->insertId();

    //engine::debug_printArray($data['materials']);
    //exit;

    foreach($pp['data']['materials']['rows'] as $material){

        engine::DB()->query('INSERT INTO @[prefix]specification_materials
             (`specificationId`, `materialArticle`, materialId, `area`, `weight`, `length`, `quantity`) VALUES
             (?i, ?s, ?s, 0, 0, 0, ?s)',
            $specificationId, $material['product']['article'], $material['product']['id'], $material['quantity']
        );
    }

    engine::TG()->sendMessage(
        engine::format_user(engine::USERS()->getCurrentUser()['id']) . ' загрузил спецификацию <a href="'.engine::CONFIG()['main']['mainAddr'].'/index.php?component=factory&page=specification&id='.$specificationId.'">'.$modName.'R'.$revision.'</a> для <a href="'.engine::CONFIG()['main']['mainAddr'].'/index.php?component=moysklad&page=product&productId='.$pp['productId'].'">'.$pp['name'].'</a>'
    );



    exit(json_encode([
        'status'=>true,
        'message'=>'Успешный успех',
    ]));
}catch(Exception $ex){
    exit(json_encode([
        'status'=>false,
        'message'=>$ex->getMessage(),
        'stackTrace' => $ex->getTraceAsString()
    ]));
}